### ISSUE TITLE
need update screenshot for executive hello first time

### ISSUE THREAD

**Issue by Apeshere** [ubuntu/codelabs#10]
![image](https://cloud.githubusercontent.com/assets/19166875/20749848/f0590350-b6eb-11e6-907a-c12d37373208.png) screenshot from step three of Create your first snap codelab: http://localhost:8123/codelabs/create-first-snap#2
this above error message can't not be produced, a different error message appears during this step.

**Comment by didrocks** [comment]
Can you copy the exact error message on your vanilla machine?

**Comment by Apeshere** [comment]
april@april-ThinkPad-T440:~/hello$ snap list
Name           Version  Rev  Developer  Notes
hello          2.10     x1              devmode
snap-codelabs  1.0      4    didrocks   -
ubuntu-core    16.04.1  423  canonical  -
april@april-ThinkPad-T440:~/hello$ hello
The program 'hello' can be found in the following packages:
 * hello
 * hello-traditional
Try: sudo apt install <selected package>

Here it is.

**Comment by didrocks** [comment]
Thanks! I think that's not exactly what is written by command not found though :/ I'll look myself at the exact content thus.

**Comment by didrocks** [comment]
ah, got it, the inferior and superior signs were stripped by github, you need to use code comment when quoting the command line :)

**Comment by didrocks** [comment]
Fixed (added a section on ubuntu desktop, as ubuntu core will have the command not found result)
