### ISSUE TITLE
Minor Ubuntu Core Getting Started tutorial issue

### ISSUE THREAD

**Issue by EmEngineer** [ubuntu/codelabs#17]
I am testing Ubuntu Core 16.04 on VirtualBox.
There is something that may not be apparent to Ubuntu newcomers on the following page:
https://tutorials.ubuntu.com/tutorial/create-first-snap#1

Before one does
"sudo apt install snapcraft build-essential"
it is necessary to do 
"sudo apt-get update"
but that is MISSING in the tutorial.

Without running "sudo apt-get update" the snapcraft and build-essential packages will not be found.

**Comment by didrocks** [comment]
Nicely spotted! (btw, you can just run `sudo apt update` now ;)). Fixing it, thanks for reporting it :)

**Comment by didrocks** [comment]
fixed in upstream documentation, it will be refreshed on the website as soon as the webteam does it. Thanks again :)
