### ISSUE TITLE
Local installation of snaps require --dangerous (--force-dangerous)

### ISSUE THREAD

**Issue by arapulido** [ubuntu/codelabs#5]
On the "Creating your first snap" tutorial, when installing your first snap the command it is recommended to you to use is: "sudo snap install --devmode hello_2.10_amd64.snap", but that won't work, as installing local snaps now requires --force-dangerous (that I have heard that it will move to --dangerous)

**Comment by didrocks** [comment]
Hey Ara!
It's actually a little bit more complicated than this (at least, with snapd master, which I'm running):
- if you are specifying `--devmode`, `--dangerous` is implied.
- if your application is confined and you want to install a local version, you need to use this `--dangerous` option.

A new snapd version is supposed to be released shortly (I don't know how the intermediate one you have is behaving regarding to that). I'm going to refresh the codelab with that taken into acount (and adding the new grade keyword as well)

**Comment by didrocks** [comment]
This is now done in the source spreadsheet codelab.
