### ISSUE TITLE
Output not formatted correctly 

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/codelabs#9]
Create your first snap --> 3. Building a snap is easy
Scroll down to see output of `sudo snap install --devmode hello_2.10_amd64.snap` command.
Columns for Rev, Developer and Notes are messed up.
Screenshot: 
![wrong-output](https://cloud.githubusercontent.com/assets/1629120/20527322/d19622ea-b0bf-11e6-8932-f567a3f3ade8.png)

**Comment by didrocks** [comment]
Thanks for your feedback! I'll have a look at why the result is the following and how to get it fixed.

**Comment by didrocks** [comment]
Updated and aligned again, a recent update broke it :)
A new update should come today with the codelab. Thanks again
